$words = {
    'riem' => { 
	'text' => 'riem',
	'file' => 'Foto_riem.jpg',
	'license' => 'ccbysa20',
	'author' => 'mtnclimb007',
	'source' => 'http://www.flickr.com/photos/mtnclimb007/6397041/',
    },
    'raam' => {
	'text' => 'raam',
	'file' => 'Foto_raam.jpg',
	'license' => 'ccbysa20',
	'author' => 'pink_dispatcher',
	'source' => 'http://www.flickr.com/photos/pink_dispatcher/267251187/',
    },
    'ram' => {
	'text' => 'ram',
	'file' => 'Foto_ram.jpg',
	'license' => 'ccby20',
	'author' => 'frield',
	'source' => 'http://www.flickr.com/photos/frield/12026489/',
    },
    'rem' => {
	'text' => 'rem',
	'file' => 'Foto_fietsrem.jpg',
	'license' => 'ccbysa20',
	'author' => 'fihu',
	'source' => 'http://www.flickr.com/photos/fihu/8733998/',
    },
    'room' => {
	'text' => 'room',
	'file' => 'Foto_aardbeien_met_room.jpg',
	'license' => 'ccbysa20',
	'author' => 'peterallen',
	'source' => 'http://www.flickr.com/photos/peterallen/169820856/',
    },
    'beuk' => {
	'text' => 'beuk',
	'file' => 'Foto_beuk.jpg',
	'license' => 'ccby20',
	'author' => 'stuant63',
	'source' => 'http://www.flickr.com/photos/stuant63/235371427/',
    },
    'boek' => {
	'text' => 'boek',
	'file' => 'Foto_boek.jpg',
	'license' => 'ccbysa20',
	'author' => 'moonpointer',
	'source' => 'http://www.flickr.com/photos/moonpointer/61757586/',
    },
    'buik' => {
	'text' => 'buik',
	'file' => 'Foto_buik.jpg',
	'license' => 'ccbysa20',
	'author' => 'brooke',
	'source' => 'http://www.flickr.com/photos/brooke/42864825/',
    },
    'bek' => {
	'text' => 'bek',
	'file' => 'Foto_bek.jpg',
	'license' => 'ccbysa20',
	'author' => 'malingering',
	'source' => 'http://www.flickr.com/photos/malingering/227816262/',
    },
    'beek' => {
	'text' => 'beek',
	'file' => 'Foto_beek.jpg',
	'license' => 'ccbysa20',
	'author' => 'pfly',
	'source' => 'http://www.flickr.com/photos/pfly/51659046/',
    },
    'bok' => {
	'text' => 'bok',
	'file' => 'Foto_bok.jpg',
	'license' => 'ccbysa20',
	'author' => 'worldheritage-forum',
	'source' => 'http://www.flickr.com/photos/worldheritage-forum/146980679/',
    },
    'bak' => {
	'text' => 'bak',
	'file' => 'Foto_bak.jpg',
	'license' => 'ccbysa20',
	'author' => 'snowday',
	'source' => 'http://www.flickr.com/photos/snowday/85464604',
    },

 
    'aap' => {
	'text' => 'aap',
	'file' => 'Foto_aap.jpg',
	'license' => 'ccbysa20',
	'author' => 'jluster',
	'source' => 'http://www.flickr.com/photos/jluster/13606646/',
    },   
    'haar' => {
	'text' => 'haar',
	'file' => 'Foto_haar.jpg',
	'license' => 'ccbysa20',
	'author' => 'strph',
	'source' => 'http://www.flickr.com/photos/strph/284792220/',
    },   
    'geel' => {
	'text' => 'geel',
	'file' => 'Tekening_geel.png',
	'license' => 'pd',
	'author' => '',
	'source' => '',
    },   
    'geit' => {
	'text' => 'geit',
	'file' => 'Foto_geit.jpg',
	'license' => 'ccbysa20',
	'author' => 'tillwe',
	'source' => 'http://www.flickr.com/photos/tillwe/38540505/',
    },   
    'sik' => {
	'text' => 'sik',
	'file' => 'Foto_sik.jpg',
	'license' => 'ccbysa20',
	'author' => 'tillwe',
	'source' => 'http://www.flickr.com/photos/tillwe/38540505/',
    },   
    'stuur' => {
	'text' => 'stuur',
	'file' => 'Foto_stuur.jpg',
	'license' => 'ccbysa20',
	'author' => 'fihu',
	'source' => 'http://www.flickr.com/photos/fihu/8733998/',
    },   
    'stier' => {
	'text' => 'stier',
	'file' => 'Foto_stier.jpg',
	'license' => 'ccbysa20',
	'author' => 'gruban',
	'source' => 'http://www.flickr.com/photos/gruban/14293144/',
    },   
    'ster' => {
	'text' => 'ster',
	'file' => 'Foto_ster.jpg',
	'license' => 'ccbysa20',
	'author' => 'foolfillment',
	'source' => 'http://www.flickr.com/photos/foolfillment/71456223/',
    },   
    'sok' => {
	'text' => 'sok',
	'file' => 'Foto_sok.jpg',
	'license' => 'ccbysa20',
	'author' => 'ejchang',
	'source' => 'http://www.flickr.com/photos/ejchang/215044115/',
    },   
    'pen' => {
	'text' => 'pen',
	'file' => 'Foto_pen.jpg',
	'license' => 'ccbysa20',
	'author' => 'yisrus',
	'source' => 'http://www.flickr.com/photos/yisris/267108081/',
    },   
    'pan' => {
	'text' => 'pan',
	'file' => 'Foto_pan.jpg',
	'license' => 'pd',
	'author' => 'Wilfred S Pau',
	'source' => 'http://en.wikipedia.org/wiki/Image:Frying_pan.jpeg'
    },   
    'muur' => {
	'text' => 'muur',
	'file' => 'Foto_muur.jpg',
	'license' => 'ccbysa20',
	'author' => 'stubbsuk',
	'source' => 'http://www.flickr.com/photos/stubbsuk/72991855/',
    },
    'mier' => {
	'text' => 'mier',
	'file' => 'Foto_mier.jpg',
	'license' => 'ccbysa20',
	'author' => 'mahalie',
	'source' => 'http://www.flickr.com/photos/mahalie/148016946/',
    },   
    'meer' => {
	'text' => 'meer',
	'file' => 'Foto_meer.jpg',
	'license' => 'ccbysa20',
	'author' => 'amitbelani',
	'source' => 'http://www.flickr.com/photos/amitbelani/142476597/',
    },   
    'moer' => {
	'text' => 'moer',
	'file' => 'Foto_moer.jpg',
	'license' => 'ccbysa20',
	'author' => 'q8',
	'source' => 'http://www.flickr.com/photos/8/7421516/',
    },   
    'bout' => {
	'text' => 'bout',
	'file' => 'Foto_bout.jpg',
	'license' => 'ccbysa20',
	'author' => 'q8',
	'source' => 'http://www.flickr.com/photos/8/7421516/',
    },   
    'pit' => {
	'text' => 'pit',
	'file' => 'Foto_pruimpit.jpg',
	'license' => 'ccbysa20',
	'author' => 'david_wilmot',
	'source' => 'http://www.flickr.com/photos/david_wilmot/282578404/
',
    },   
    'hond' => {
	'text' => 'hond',
	'file' => 'Foto_hond.jpg',
	'license' => 'ccbysa20',
	'author' => 'zivpu',
	'source' => 'http://www.flickr.com/photos/zivpu/143909206/',
    },   
    'pot' => {
	'text' => 'pot',
	'file' => 'Foto_pot.jpg',
	'license' => 'ccbysa20',
	'author' => 'qousqous',
	'source' => 'http://www.flickr.com/photos/qousqous/113848074/',
    },   
    'put'=> {
	'text' => 'put',
	'file' => 'Foto_put.jpg',
	'license' => 'ccbysa20',
	'author' => 'turningpoint',
	'source' => 'http://www.flickr.com/photos/turningpoint/2274637/',
    },   
    'bal' => {
	'text' => 'bal',
	'file' => 'Foto_bal.jpg',
	'license' => 'ccbysa20',
	'author' => 'trommetter',
	'source' => 'http://www.flickr.com/photos/trommetter/32346120/',
    },
    'bel' => {
	'text' => 'bel',
	'file' => 'Foto_bel.jpg',
	'license' => 'ccbysa20',
	'author' => 'avalonstar',
	'source' => 'http://www.flickr.com/photos/avalonstar/27599164/',
    },
    'vis' => {
	'text' => 'vis',
	'file' => 'Foto_vis.jpg',
	'license' => 'gfdl',
	'author' => 'Jdiemer',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Guppy-male.jpg',
    },
    'vos' => {
	'text' => 'vos',
	'file' => 'Foto_vos.jpg',
	'license' => 'ccbysa20',
	'author' => 'drome',
	'source' => 'http://www.flickr.com/photos/drome/200423147/',
    },
    'vies' => {
	'text' => 'vies',
	'file' => 'Foto_vies.jpg',
	'license' => 'ccby20',
	'author' => 'basykes',
	'source' => 'http://www.flickr.com/photos/basykes/16110273/',
    },
    'vaas' => {
	'text' => 'vaas',
	'file' => 'Foto_vaas.jpg',
	'license' => 'ccbysa20',
	'author' => 'globetrotter1937',
	'source' => 'http://www.flickr.com/photos/globetrotter1937/243698230/',
    },
    'roos' => {
	'text' => 'roos',
	'file' => 'Foto_roos.jpg',
	'license' => 'ccbysa20',
	'author' => 'abardwell',
	'source' => 'http://www.flickr.com/photos/abardwell/141158506/',
    },
    'maan' => {
	'text' => 'maan',
	'file' => 'Foto_maan.jpg',
	'license' => 'ccbysa20',
	'author' => 'manannan_alias_fanc',
	'source' => 'http://www.flickr.com/photos/manannan_alias_fanch/288864074/',
    },
    'boom' => {
	'text' => 'boom',
	'file' => 'Foto_boom.jpg',
	'license' => 'ccbysa20',
	'author' => 'alphageek',
	'source' => 'http://www.flickr.com/photos/alphageek/18860942/',
    },
    'ik' => {
	'text' => 'ik',
	'file' => 'Foto_ik.jpg',
	'license' => 'ccbysa20',
	'author' => 'nabeel',
	'source' => 'http://www.flickr.com/photos/nabeel/42672704/',
    },
    'teen' => {
	'text' => 'teen',
	'file' => 'Foto_teen.jpg',
	'license' => 'ccbysa20',
	'author' => 'andy_5322',
	'source' => 'http://www.flickr.com/photos/andy_5322/113339784/',
    },
    'neus' => {
	'text' => 'neus',
	'file' => 'Foto_neus.jpg',
	'license' => 'ccbysa20',
	'author' => 'denn',
	'source' => 'http://www.flickr.com/photos/denn/22614998/',
    },
    'oog' => {
	'text' => 'oog',
	'file' => 'Foto_oog.jpg',
	'license' => 'ccbysa20',
	'author' => 'globetrotter1937',
	'source' => 'http://www.flickr.com/photos/globetrotter1937/145439662/',
    },
    'aap' => {
	'text' => 'aap',
	'file' => 'Foto_aap.jpg',
	'license' => 'ccbysa20',
	'author' => 'jluster',
	'source' => 'http://www.flickr.com/photos/jluster/13606646/',
    },
    'doos' => {
	'text' => 'doos',
	'file' => 'Foto_doos.jpg',
	'license' => 'ccbysa20',
	'author' => 'oxborrow',
	'source' => 'http://www.flickr.com/photos/oxborrow/53015951/',
    },
    'taart' => {
	'text' => 'taart',
	'file' => 'Foto_taart.jpg',
	'license' => 'ccbysa20',
	'author' => 'augie',
	'source' => 'http://www.flickr.com/photos/augie/181886409/',
    },
    'koek' => {
	'text' => 'koek',
	'file' => 'Foto_koek.jpg',
	'license' => 'ccbysa20',
	'author' => 'monicamartins',
	'source' => 'http://www.flickr.com/photos/monicamartins/263980066/',
    },
    'ijs' => {
	'text' => 'ijs',
	'file' => 'Foto_ijs.jpg',
	'license' => 'ccbysa20',
	'author' => 'stuart_spivack',
	'source' => 'http://www.flickr.com/photos/stuart_spivack/90077207',
    },
    'ui' => {
	'text' => 'ui',
	'file' => 'Foto_ui.jpg',
	'license' => 'ccbysa20',
	'author' => 'ecletical',
	'source' => 'http://www.flickr.com/photos/eclectical/92062837/',
    },
    'ei' => {
	'text' => 'ei',
	'file' => 'Foto_ei.jpg',
	'license' => 'ccbysa20',
	'author' => 'cyberinsekt',
	'source' => 'http://www.flickr.com/photos/cyberinsekt/156789795/',
    },
    'zeep' => {
	'text' => 'zeep',
	'file' => 'Foto_zeep.jpg',
	'license' => 'ccbysa20',
	'author' => 'azadam',
	'source' => 'http://www.flickr.com/photos/azadam/10277259/',
    },
    'poes' => {
	'text' => 'poes',
	'file' => 'Foto_poes.jpg',
	'license' => 'ccbysa20',
	'author' => 'salimfadhley',
	'source' => 'http://www.flickr.com/photos/salimfadhley/27839091/',
    },
    'kei' => {
	'text' => 'kei',
	'file' => 'Foto_kei.jpg',
	'license' => 'ccbysa20',
	'author' => 'aardvarkoffnord',
	'source' => 'http://www.flickr.com/photos/aardvarkoffnord/289798482',
    },
    'eik' => {
	'text' => 'eik',
	'file' => 'Foto_eik.jpg',
	'license' => 'ccbysa20',
	'author' => 'pickles_pics',
	'source' => 'http://www.flickr.com/photos/pickles_pics/138397762/',
    },
    'spin' => {
	'text' => 'spin',
	'file' => 'Foto_spin.jpg',
	'license' => 'ccbysa20',
	'author' => 'andreweason',
	'source' => 'http://www.flickr.com/photos/andreweason/34262004/',
    },
    'been' => {
	'text' => 'been',
	'file' => 'Foto_been.jpg',
	'license' => 'ccbysa20',
	'author' => 'mrimperial',
	'source' => 'http://www.flickr.com/photos/mrimperial/103472723/',
    },
    'voet' => {
	'text' => 'voet',
	'file' => 'Foto_voet.jpg',
	'license' => 'ccbysa20',
	'author' => 'berlin78',
	'source' => 'http://www.flickr.com/photos/berlin78/156585499',
    },
    'poot' => {
	'text' => 'poot',
	'file' => 'Foto_poot.jpg',
	'license' => 'ccbysa20',
	'author' => 'strph',
	'source' => 'http://www.flickr.com/photos/strph/4135381/',
    },
    'rok' => {
	'text' => 'rok',
	'file' => 'Foto_rok.jpg',
	'license' => 'ccby20',
	'author' => 'cayce',
	'source' => 'http://www.flickr.com/photos/cayce/44905410',
    },
    'vuur' => {
	'text' => 'vuur',
	'file' => 'Foto_vuur.jpg',
	'license' => 'ccby20',
	'author' => 'maxf',
	'source' => 'http://www.flickr.com/photos/maxf/288915809/',
    },
    'rook' => {
	'text' => 'rook',
	'file' => 'Foto_rook.jpg',
	'license' => 'ccbysa20',
	'author' => 'uwehermann',
	'source' => 'http://www.flickr.com/photos/uwehermann/132243416/',
    },
    'hek' => {
	'text' => 'hek',
	'file' => 'Foto_hek.jpg',
	'license' => 'ccbysa20',
	'author' => '77704362@N00',
	'source' => 'http://www.flickr.com/photos/77704362@N00/54019118/',
    },
    'bos' => {
	'text' => 'bos',
	'file' => 'Foto_bos.jpg',
	'license' => 'ccby20',
	'author' => 'tallkev',
	'source' => 'http://www.flickr.com/photos/tallkev/270039018/',
    },
    'boos' => {
	'text' => 'boos',
	'file' => 'Foto_boos.jpg',
	'license' => 'ccbysa20',
	'author' => 'skippy',
	'source' => 'http://www.flickr.com/photos/skippy/196481731/',
    },
    'huis' => {
	'text' => 'huis',
	'file' => 'Foto_huis.jpg',
	'license' => 'ccbysa20',
	'author' => 'qousqous',
	'source' => 'http://www.flickr.com/photos/qousqous/57327562/',
    },
    'weg' => {
	'text' => 'weg',
	'file' => 'Foto_weg.jpg',
	'license' => 'ccbysa20',
	'author' => 'wiesmann',
	'source' => 'http://www.flickr.com/photos/wiesmann/195209391/',
    },
    'tak' => {
	'text' => 'tak',
	'file' => 'Foto_tak.jpg',
	'license' => 'ccbysa20',
	'author' => 'stinkypeter',
	'source' => 'http://www.flickr.com/photos/stinkypeter/133097148/',
    },
    'hut' => {
	'text' => 'hut',
	'file' => 'Foto_hut.jpg',
	'license' => 'ccbysa20',
	'author' => 'lintbrush',
	'source' => 'http://www.flickr.com/photos/lintbrush/196818845/',
    },
    'klok' => {
	'text' => 'klok',
	'file' => 'Foto_klok.jpg',
	'license' => 'ccbysa20',
	'author' => 'zixi',
	'source' => 'http://www.flickr.com/photos/zixi/247661086/',
    },
    'jas' => {
	'text' => 'jas',
	'file' => 'Foto_jas.jpg',
	'license' => 'ccbysa20',
	'author' => 'sfllaw',
	'source' => 'http://www.flickr.com/photos/sfllaw/122425051/',
    },
    'reus' => {
	'text' => 'reus',
	'file' => 'Foto_reus.jpg',
	'license' => 'ccbysa20',
	'author' => 'stinkypeter',
	'source' => 'http://www.flickr.com/photos/stinkypeter/147654404/',
    },
    'mier' => {
	'text' => 'mier',
	'file' => 'Foto_mier.jpg',
	'license' => 'ccbysa20',
	'author' => 'mahalie',
	'source' => 'http://www.flickr.com/photos/mahalie/148016946/',
    },
    'hout' => {
	'text' => 'hout',
	'file' => 'Foto_hout.jpg',
	'license' => 'ccby20',
	'author' => 'ezlens',
	'source' => 'http://www.flickr.com/photos/ezlens/105053000/',
    },
    'bier' => {
	'text' => 'bier',
	'file' => 'Foto_bier.jpg',
	'license' => 'ccbysa20',
	'author' => 'swanksalot',
	'source' => 'http://www.flickr.com/photos/swanksalot/163883417/',
    },
    'duif' => {
	'text' => 'duif',
	'file' => 'Foto_duif.jpg',
	'license' => 'ccbysa20',
	'author' => 'grendelkhan',
	'source' => 'http://www.flickr.com/photos/grendelkhan/136930419/',
    },
    'uil' => {
	'text' => 'uil',
	'file' => 'Foto_uil.jpg',
	'license' => 'ccbysa20',
	'author' => 'eifion',
	'source' => 'http://www.flickr.com/photos/eifion/158217225/',
    },
    'pauw' => {
	'text' => 'pauw',
	'file' => 'Foto_pauw.jpg',
	'license' => 'ccbysa20',
	'author' => 'jameschip',
	'source' => 'http://www.flickr.com/photos/jameschip/129114512/',
    },
    'bijl' => {
	'text' => 'bijl',
	'file' => 'Foto_bijl.jpg',
	'license' => 'ccbysa20',
	'author' => 'bjornb',
	'source' => 'http://www.flickr.com/photos/bjornb/143061092',
    },
    'ring' => {
	'text' => 'ring',
	'file' => 'Foto_ring.jpg',
	'license' => 'ccbysa20',
	'author' => 'strph',
	'source' => 'http://www.flickr.com/photos/strph/13429148/',
    },
    'kas' => {
	'text' => 'kas',
	'file' => 'Foto_kas.jpg',
	'license' => 'ccbysa20',
	'author' => 'dougn',
	'source' => 'http://www.flickr.com/photos/dougn/153507381',
    },
    'man' => {
	'text' => 'man',
	'file' => 'Foto_man.jpg',
	'license' => 'ccbysa20',
	'author' => 'tasteful_tn',
	'source' => 'http://www.flickr.com/photos/tasteful_tn/109209934',
    },
    'kaas' => {
	'text' => 'kaas',
	'file' => 'Foto_kaas.jpg',
	'license' => 'ccbysa20',
	'author' => 'gareandkitty',
	'source' => 'http://www.flickr.com/photos/gareandkitty/244556573/',
    },
    'klauw' => {
	'text' => 'klauw',
	'file' => 'Foto_klauw.jpg',
	'license' => 'ccbysa20',
	'author' => 'delta407',
	'source' => 'http://www.flickr.com/photos/delta407/285070294/',
    },
    'druif' => {
	'text' => 'druif',
	'file' => 'Foto_druif.jpg',
	'license' => 'ccbysa20',
	'author' => 'pfly',
	'source' => 'http://www.flickr.com/photos/pfly/195777261/',
    },
    'muis' => {
	'text' => 'muis',
	'file' => 'Foto_muis.jpg',
	'license' => 'ccbysa20',
	'author' => 'e3000',
	'source' => 'http://www.flickr.com/photos/e3000/99284256/',
    },
    'hak' => {
	'text' => 'hak',
	'file' => 'Foto_hak.png',
	'license' => 'ccbysa20',
	'author' => 'dotbaz',
	'source' => 'http://www.flickr.com/photos/dotbaz/52197840/',
    },
    'haak' => {
	'text' => 'haak',
	'file' => 'Foto_haak.jpg',
	'license' => 'ccbysa20',
	'author' => 'benfrantzdale',
	'source' => 'http://www.flickr.com/photos/benfrantzdale/253792345',
    },
    'een' => {
	'text' => 'een',
	'file' => 'Tekening_een.png',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'twee' => {
	'text' => 'twee',
	'file' => 'Tekening_twee.png',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'drie' => {
	'text' => 'drie',
	'file' => 'Tekening_drie.png',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'vier' => {
	'text' => 'vier',
	'file' => 'Tekening_vier.png',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'vijf' => {
	'text' => 'vijf',
	'file' => 'Tekening_vijf.png',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'zes' => {
	'text' => 'zes',
	'file' => 'Tekening_zes.png',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'acht' => {
	'text' => 'acht',
	'file' => 'Tekening_acht.png',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'tien' => {
	'text' => 'tien',
	'file' => 'Tekening_tien.png',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'blauw' => {
	'text' => 'blauw',
	'file' => 'Tekening_blauw.png',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'bruin' => {
	'text' => 'bruin',
	'file' => 'Tekening_bruin.png',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'geel' => {
	'text' => 'geel',
	'file' => 'Tekening_geel.png',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'gil' => {
	'text' => 'gil',
	'file' => 'Foto_gillen.png',
	'license' => 'ccbysa20',
	'author' => '25654418@N00',
	'source' => 'http://www.flickr.com/photos/25654418@N00/183360647/',
    },
    'boer' => {
	'text' => 'boer',
	'file' => 'Foto_boer.jpg',
	'license' => 'ccby20',
	'author' => 'slemerick',
	'source' => 'http://www.flickr.com/photos/slemerick/103475737/',
    },
    'boot' => {
	'text' => 'boot',
	'file' => 'Foto_boot.jpg',
	'license' => 'ccbysa20',
	'author' => 'sararichards',
	'source' => 'http://www.flickr.com/photos/sararichards/185027276/',
    },
    'bot' => {
	'text' => 'bot',
	'file' => 'Foto_bot.jpg',
	'license' => 'ccbysa20',
	'author' => '',
	'source' => '',
    },
    'koe' => {
	'text' => 'koe',
	'file' => 'Foto_koe.jpg',
	'license' => 'ccbysa20',
	'author' => 'peterallen',
	'source' => 'http://www.flickr.com/photos/peterallen/289840692/',
    },
    'nek' => {
	'text' => 'nek',
	'file' => 'Foto_nek.jpg',
	'license' => 'ccbysa20',
	'author' => 'loungerie',
	'source' => 'http://www.flickr.com/photos/loungerie/33593482/',
    },
    'geld' => {
	'text' => 'geld',
	'file' => 'Foto_geld.jpg',
	'license' => 'ccbysa20',
	'author' => 'stokedfish',
	'source' => 'http://www.flickr.com/photos/stokedfish/145389483/',
    },
    'bot' => {
	'text' => 'bot',
	'file' => 'Foto_bot.jpg',
	'license' => 'ccby20',
	'author' => 'jonasb',
	'source' => 'http://www.flickr.com/photos/jonasb/156757632/',
    },
    'deur' => {
	'text' => 'deur',
	'file' => 'Foto_deur.jpg',
	'license' => 'ccbysa20',
	'author' => 'thomieh',
	'source' => 'http://www.flickr.com/photos/thomieh/152613455/',
    },
    'mes' => {
	'text' => 'mes',
	'file' => 'Foto_mes.jpg',
	'license' => 'ccbysa20',
	'author' => 'yashima',
	'source' => 'http://www.flickr.com/photos/yashima/30192914/',
    },
    'soep' => {
	'text' => 'soep',
	'file' => 'Foto_soep.jpg',
	'license' => 'ccbysa20',
	'author' => 'digitalcameraguy',
	'source' => 'http://www.flickr.com/photos/digitalcameraguy/48196068/',
    },
    'rij' => {
	'text' => 'rij',
	'file' => 'Foto_rij.jpg',
	'license' => 'ccbysa20',
	'author' => 'chrisandhilleary',
	'source' => 'http://www.flickr.com/photos/chrisandhilleary/205867820/',
    },
    'pap' => {
	'text' => 'pap',
	'file' => 'Foto_pap.jpg',
	'license' => 'ccbysa20',
	'author' => 'risager',
	'source' => 'http://www.flickr.com/photos/risager/286575118/',
    },
    'pijp' => {
	'text' => 'pijp',
	'file' => 'Foto_pijp.jpg',
	'license' => 'pd',
	'author' => 'Frotz661',
	'source' => 'http://en.wikipedia.org/wiki/Image:Calabash-pipe.jpg',
    },
    'noot' => {
	'text' => 'noot',
	'file' => 'Foto_noot.jpg',
	'license' => 'gfdl',
	'author' => 'Fir0002',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Walnut03.jpg',
    },
    'dijk' => {
	'text' => 'dijk',
	'file' => 'Foto_dijk.jpg',
	'license' => 'ccbysa20',
	'author' => 'photocapy',
	'source' => 'http://www.flickr.com/photos/photocapy/57654079/',
    },
    'kers' => {
	'text' => 'kers',
	'file' => 'Foto_kers.jpg',
	'license' => 'ccbysa20',
	'author' => 'strph',
	'source' => 'http://www.flickr.com/photos/strph/206264002/',
    },
    'bes' => {
	'text' => 'bes',
	'file' => 'Foto_bes.jpg',
	'license' => 'ccbysa20',
	'author' => 'mpich3',
	'source' => 'http://www.flickr.com/photos/mpich3/201291664/',
    },
    'bus' => {
	'text' => 'bus',
	'file' => 'Foto_bus.jpg',
	'license' => 'ccbysa20',
	'author' => 'fpalazzi',
	'source' => 'http://www.flickr.com/photos/fpalazzi/32874700/',
    },
    'top' => {
	'text' => 'top',
	'file' => 'Foto_top.jpg',
	'license' => 'ccbysa20',
	'author' => 'paulmannix',
	'source' => 'http://www.flickr.com/photos/paulmannix/261314905/',
    },
    'post' => {
	'text' => 'post',
	'file' => 'Foto_post.jpg',
	'license' => 'ccbysa20',
	'author' => 'debaird',
	'source' => 'http://www.flickr.com/photos/debaird/174128903/',
    },
    'buis' => {
	'text' => 'buis',
	'file' => 'Foto_buis.jpg',
	'license' => 'ccbysa20',
	'author' => 'wannaoreo',
	'source' => 'http://www.flickr.com/photos/wannaoreo/63078832/',
    },
    'brief' => {
	'text' => 'brief',
	'file' => 'Foto_brief.jpg',
	'license' => 'ccbysa20',
	'author' => 'vincentmaher',
	'source' => 'http://www.flickr.com/photos/vincentmaher/109093159/',
    },
    'kin' => {
	'text' => 'kin',
	'file' => 'Foto_kin.jpg',
	'license' => 'ccby20',
	'author' => 'jonmclean',
	'source' => 'http://www.flickr.com/photos/jonmclean/229583220/',
    },
    'kaart' => {
	'text' => 'kaart',
	'file' => 'Foto_kaart.png',
	'license' => 'ccbysa20',
	'author' => 'tobin',
	'source' => 'http://www.flickr.com/photos/tobin/175785773/',
    },
    'uit' => {
	'text' => 'uit',
	'file' => 'Foto_uit.jpg',
	'license' => 'ccbysa20',
	'author' => 'irisheyes',
	'source' => 'http://www.flickr.com/photos/irisheyes/164046533',
    },
    'aan' => {
	'text' => 'aan',
	'file' => 'Foto_aan.jpg',
	'license' => 'ccbysa20',
	'author' => 'peterallen',
	'source' => 'http://www.flickr.com/photos/peterallen/194239785/',
    },
    'stop' => {
	'text' => 'stop',
	'file' => 'Foto_stop.jpg',
	'license' => 'ccbysa20',
	'author' => 'uscfan',
	'source' => 'http://www.flickr.com/photos/uscfan/16188057/',
    },
    'stil' => {
	'text' => 'stil',
	'file' => 'Foto_stil.jpg',
	'license' => 'ccbysa20',
	'author' => 'ko_an',
	'source' => 'http://www.flickr.com/photos/ko_an/108335243/',
    },
    'kots' => {
	'text' => 'kots',
	'file' => 'Foto_kots.jpg',
	'license' => 'ccbysa20',
	'author' => 'mugley',
	'source' => 'http://www.flickr.com/photos/mugley/74651701/',
    },
    'stok' => {
	'text' => 'stok',
	'file' => 'Foto_stok.jpg',
	'license' => 'ccby20',
	'author' => 'raindog808',
	'source' => 'http://www.flickr.com/photos/raindog808/263092432/',
    },
    'park' => {
	'text' => 'park',
	'file' => 'Foto_park.jpg',
	'license' => 'ccbysa20',
	'author' => 'grampymoose',
	'source' => 'http://www.flickr.com/photos/grampymoose/268178818/',
    },
    'tuin' => {
	'text' => 'tuin',
	'file' => 'Foto_tuin.jpg',
	'license' => 'ccbysa20',
	'author' => '29278394@N00',
	'source' => 'http://www.flickr.com/photos/29278394@N00/195406937/',
    },
    'zon' => {
	'text' => 'zon',
	'file' => 'Foto_zon.jpg',
	'license' => 'ccbysa20',
	'author' => 'lachlanhardy',
	'source' => 'http://www.flickr.com/photos/lachlanhardy/271794120/

',
    },
    'gras' => {
	'text' => 'gras',
	'file' => 'Foto_gras.jpg',
	'license' => 'ccbysa20',
	'author' => 'mewzii',
	'source' => 'http://www.flickr.com/photos/mewzii/149568295/',
    },
    'trui' => {
	'text' => 'trui',
	'file' => 'Foto_trui.jpg',
	'license' => 'ccbysa20',
	'author' => 'annarama',
	'source' => 'http://www.flickr.com/photos/annarama/250600155/',
    },
    'boog' => {
	'text' => 'boog',
	'file' => 'Foto_boog.jpg',
	'license' => 'ccbysa20',
	'author' => 'fancythis',
	'source' => 'http://www.flickr.com/photos/fancythis/22206336/',
    },
    'sap' => {
	'text' => 'sap',
	'file' => 'Foto_sap.jpg',
	'license' => 'ccbysa20',
	'author' => 'stubbsuk',
	'source' => 'http://www.flickr.com/photos/stubbsuk/191584630/',
    },
    'wijn' => {
	'text' => 'wijn',
	'file' => 'Foto_wijn.jpg',
	'license' => 'ccbysa20',
	'author' => 'garyjwood',
	'source' => 'http://www.flickr.com/photos/garyjwood/170012861/',
    },
    'mok' => {
	'text' => 'mok',
	'file' => 'Foto_mok.jpg',
	'license' => 'ccbysa20',
	'author' => 'awayken',
	'source' => 'http://www.flickr.com/photos/awayken/82965768/',
    },
    'melk' => {
	'text' => 'melk',
	'file' => 'Foto_melk.jpg',
	'license' => 'ccbysa20',
	'author' => 'stuart_spivack',
	'source' => 'http://www.flickr.com/photos/stuart_spivack/235481265
/',
    },
    'glas' => {
	'text' => 'glas',
	'file' => 'Foto_glas.jpg',
	'license' => 'ccbysa20',
	'author' => 'loopzilla',
	'source' => 'http://www.flickr.com/photos/loopzilla/141508160/',
    },
    'kom' => {
	'text' => 'kom',
	'file' => 'Foto_kom.jpg',
	'license' => 'ccbysa20',
	'author' => 'liralenli',
	'source' => 'http://www.flickr.com/photos/liralenli/109776027/',
    },
    'kar' => {
	'text' => 'kar',
	'file' => 'Foto_kar.jpg',
	'license' => 'ccbysa20',
	'author' => 'ikhlasulamal',
	'source' => 'http://www.flickr.com/photos/ikhlasulamal/7792230',
    },
    'pil' => {
	'text' => 'pil',
	'file' => 'Foto_pil.jpg',
	'license' => 'ccbysa20',
	'author' => 'jackspics',
	'source' => 'http://www.flickr.com/photos/jackspics/225502941/',
    },
    'lip' => {
	'text' => 'lip',
	'file' => 'Foto_lip.jpg',
	'license' => 'ccbysa20',
	'author' => 'strph',
	'source' => 'http://www.flickr.com/photos/strph/75232395/',
    },
    'rat' => {
	'text' => 'rat',
	'file' => 'Foto_rat.jpg',
	'license' => 'ccbysa20',
	'author' => 'meerling',
	'source' => 'http://www.flickr.com/photos/meerling/164787102',
    },
    'net' => {
	'text' => 'net',
	'file' => 'Foto_net.jpg',
	'license' => 'ccbysa20',
	'author' => '25964947@N00',
	'source' => 'http://www.flickr.com/photos/25964947@N00/52915949/'
    },
    'beer' => {
	'text' => 'beer',
	'file' => 'Foto_beer.jpg',
	'license' => 'ccbysa20',
	'author' => 'jameschip',
	'source' => 'http://www.flickr.com/photos/jameschip/129121317/',
    },
    'oor' => {
	'text' => 'oor',
	'file' => 'Foto_oor.jpg',
	'license' => 'ccbysa20',
	'author' => 'jemsweb',
	'source' => 'http://www.flickr.com/photos/jemsweb/7193106/',
    },
    'vin' => {
	'text' => 'vin',
	'file' => 'Foto_vin.jpg',
	'license' => 'ccbysa20',
	'author' => 'liz',
	'source' => 'http://www.flickr.com/photos/liz/34148479/',
    },
    'peer' => {
	'text' => 'peer',
	'file' => 'Foto_peer.jpg',
	'license' => 'ccbysa20',
	'author' => 'girlgeek',
	'source' => 'http://www.flickr.com/photos/girlgeek/131901550/',
    },
    'es' => {
	'text' => 'es',
	'file' => 'Foto_es.jpg',
	'license' => 'gfdl',
	'author' => 'Georges Jansoone',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Fraxinus_excelsior11.JPEG',
    },
    'min' => {
	'text' => 'min',
	'file' => 'Tekening_min.png',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'plus' => {
	'text' => 'plus',
	'file' => 'Tekening_plus.png',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'is' => {
	'text' => 'is',
	'file' => 'Tekening_is.png',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'bom' => {
	'text' => 'bom',
	'file' => 'Foto_bom.jpg',
	'license' => 'ccbysa20',
	'author' => 'a_big_big_world',
	'source' => 'http://www.flickr.com/photos/a_big_big_world/55130474/',
    },
    'kok' => {
	'text' => 'kok',
	'file' => 'Foto_kok.jpg',
	'license' => 'ccbysa20',
	'author' => 'belisario',
	'source' => 'http://www.flickr.com/photos/belisario/130653589/',
    },
    'poep' => {
	'text' => 'poep',
	'file' => 'Foto_poep.jpg',
	'license' => 'ccbysa20',
	'author' => 'horrortaxi',
	'source' => 'http://www.flickr.com/photos/horrortaxi/150930147/',
    },
    'koor' => {
	'text' => 'koor',
	'file' => 'Foto_koor.jpg',
	'license' => 'ccbysa20',
	'author' => 'amagill',
	'source' => 'http://www.flickr.com/photos/amagill/73148941/',
    },
    'kat' => {
	'text' => 'kat',
	'file' => 'Foto_kat.jpg',	
	'license' => 'ccbysa20',
	'author' => 'storem',
	'source' => 'http://www.flickr.com/photos/storem/232512372/',
    },
    'zee' => {
	'text' => 'zee',
	'file' => 'Foto_zee.jpg',
	'license' => 'ccbysa20',
	'author' => 'robadob',
	'source' => 'http://www.flickr.com/photos/robadob/88937282/',
    },
    'mus' => {
	'text' => 'mus',
	'file' => 'Foto_mus.jpg',
	'license' => 'ccbysa20',
	'author' => 'chefranden',
	'source' => 'http://www.flickr.com/photos/chefranden/143182619/',
    },
    'lam' => {
	'text' => 'lam',
	'file' => 'Foto_lam.jpg',
	'license' => 'ccbysa20',
	'author' => 'yogi',
	'source' => 'http://www.flickr.com/photos/yogi/152076805/',
    },
    'veer' => {
	'text' => 'veer',
	'file' => 'Foto_veer.jpg',
	'license' => 'ccby20',
	'author' => 'Naomi Ibuki',
	'source' => 'http://www.flickr.com/photos/777/14111618/',
    },
    'naam' => {
	'text' => 'naam',
	'file' => 'Foto_naam.jpg',
	'license' => 'ccbysa20',
	'author' => 'tomeppy',
	'source' => 'http://www.flickr.com/photos/tomeppy/197909345/',
    },
    'doek' => {
	'text' => 'doek',
	'file' => 'Foto_doek.jpg',
	'license' => 'ccbysa20',
	'author' => 'peterallen',
	'source' => 'http://www.flickr.com/photos/peterallen/167207844/',
    },
    'dik' => {
	'text' => 'dik',
	'file' => 'Foto_dik.jpg',
	'license' => 'ccbysa20',
	'author' => 'salim',
	'source' => 'http://www.flickr.com/photos/salim/4730723/',
    },
    'mug' => {
	'text' => 'mug',
	'file' => 'Foto_mug.jpg',
	'license' => 'pd',
	'author' => '',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Aedes_aegypti_biting_human.jpg',
    },
    'kier' => {
	'text' => 'kier',
	'file' => 'Foto_kier.jpg',
	'license' => 'ccbysa20',
	'author' => 'girlreporter',
	'source' => 'http://www.flickr.com/photos/girlreporter/33557110/',
    },
    'haas' => {
	'text' => 'haas',
	'file' => 'Foto_haas.jpg',
	'license' => 'gfdl',
	'author' => 'Fmickan',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Feldhase.jpg',
    },
    'dak' => {
	'text' => 'dak',
	'file' => 'Foto_dak.jpg',
	'license' => 'ccbysa20',
	'author' => 'o2ma',
	'source' => 'http://www.flickr.com/photos/o2ma/224918622/'
    },

    'trap' => {
	'text' => 'trap',
	'file' => 'Foto_trap.jpg',
	'license' => 'ccbysa20',
	'author' => 'wmjas',
	'source' => 'http://www.flickr.com/photos/wmjas/51121989/',
    },

    'ham' => {
	'text' => 'ham',
	'file' => 'Foto_ham.jpg',
	'license' => 'ccbysa20',
	'author' => 'kentwang',
	'source' => 'http://www.flickr.com/photos/kentwang/146985608/',
    },

    'vork' => {
	'text' => 'vork',
	'file' => 'Foto_vork.jpg',
	'license' => 'ccbysa20',
	'author' => 'chodhound',
	'source' => 'http://www.flickr.com/photos/chodhound/92360064/',
    },

    'bij' => {
	'text' => 'bij',
	'file' => 'Foto_bij.jpg',
	'license' => 'pd',
	'author' => 'John Steverns',
	'source' => 'http://en.wikipedia.org/wiki/Image:061001-F-4968S-001a.jpg',
    },

    'scheel' => {
	'text' => 'scheel',
	'file' => 'Foto_scheel.jpg',
	'license' => 'ccby20',
	'author' => '40114390@N00',
	'source' => 'http://www.flickr.com/photos/40114390@N00/98841550/',
    },

    'web' => {
	'text' => 'web',
	'file' => 'Foto_web.jpg',
	'license' => 'ccbysa20',
	'author' => 'loomer',
	'source' => 'http://www.flickr.com/photos/loomer/176521805/',
    },

    'schil' => {
	'text' => 'schil',
	'file' => 'Foto_schil.jpg',
	'license' => 'ccbysa20',
	'author' => 'roland',
	'source' => 'http://www.flickr.com/photos/roland/119570504/',
    },

    'was' => {
	'text' => 'was',
	'file' => 'Foto_was.jpg',
	'license' => 'ccbysa20',
	'author' => 'smfrick',
	'source' => 'http://www.flickr.com/photos/smfrick/47763730/',
    },

    'knop' => {
	'text' => 'knop',
	'file' => 'Foto_knop.jpg',
	'license' => 'ccbysa20',
	'author' => 'tirrell',
	'source' => 'http://www.flickr.com/photos/tirrell/110622533/',
    },

    'knoop' => {
	'text' => 'knoop',
	'file' => 'Foto_knoop.jpg',
	'license' => 'ccbysa20',
	'author' => 'loungerie',
	'source' => 'http://www.flickr.com/photos/loungerie/35564386/',
    },

    'touw' => {
	'text' => 'touw',
	'file' => 'Foto_touw.jpg',
	'license' => 'ccbysa20',
	'author' => 'tallmariah',
	'source' => 'http://www.flickr.com/photos/tallmariah/171032541/',
    },

    'rijst' => {
	'text' => 'rijst',
	'file' => 'Foto_rijst.jpg',
	'license' => 'ccbysa20',
	'author' => 'joshua',
	'source' => 'http://www.flickr.com/photos/joshua/7354582/',
    },

    'mouw' => {
	'text' => 'mouw',
	'file' => 'Foto_mouw.jpg',
	'license' => 'ccbysa20',
	'author' => 'liralenli',
	'source' => 'http://www.flickr.com/photos/liralenli/121530644/',
    },

    'mat' => {
	'text' => 'mat',
	'file' => 'Foto_mat.jpg',
	'license' => 'ccbysa20',
	'author' => 'daxiang',
	'source' => 'http://www.flickr.com/photos/daxiang/17597024/',
    },

    'arm' => {
	'text' => 'arm',
	'file' => 'Foto_arm.jpg',
	'license' => 'ccbysa20',
	'author' => 'matsuyuki',
	'source' => 'http://www.flickr.com/photos/matsuyuki/162273513/',
    },

    'hart' => {
	'text' => 'hart',
	'file' => 'Foto_hart.jpg',
	'license' => 'ccbysa20',
	'author' => 'Foto_hart.jpg',
	'source' => 'http://www.flickr.com/photos/dannohung/4871353/',
    },

    'tas' => {
	'text' => 'tas',
	'file' => 'Foto_tas.jpg',
	'license' => 'ccbysa20',
	'author' => 'joodles',
	'source' => 'http://www.flickr.com/photos/joodles/254328934/',
    },

    'zak' => {
	'text' => 'zak',
	'file' => 'Foto_zak.jpg',
	'license' => 'ccbysa20',
	'author' => 'mbiddulph',
	'source' => 'http://www.flickr.com/photos/mbiddulph/247968220/',
    },

    'pak' => {
	'text' => 'pak',
	'file' => 'Foto_pak.jpg',
	'license' => 'ccbysa20',
	'author' => '3ola',
	'source' => 'http://www.flickr.com/photos/3ola/54688620/',
    },

    'kop' => {
	'text' => 'kop',
	'file' => 'Foto_kop.jpg',
	'license' => 'ccbysa20',
	'author' => 'dannyboyster',
	'source' => 'http://www.flickr.com/photos/dannyboyster/49705209',
    },

    'hoek' => {
	'text' => 'hoek',
	'file' => 'Foto_hoek.jpg',
	'license' => 'ccbysa20',
	'author' => 'orinrobertjohn',
	'source' => 'http://www.flickr.com/photos/orinrobertjohn/29769008/',
    },

    'duin' => {
	'text' => 'duin',
	'file' => 'Foto_duin.jpg',
	'license' => 'ccbysa20',
	'author' => 'theliar',
	'source' => 'http://www.flickr.com/photos/theliar/13825596/',
    },

    'kist' => {
	'text' => 'kist',
	'file' => 'Foto_kist.jpg',
	'license' => 'ccbysa20',
	'author' => 'currybet',
	'source' => 'http://www.flickr.com/photos/currybet/76536175/',
    },

    'punt' => {
	'text' => 'punt',
	'file' => 'Foto_punt.jpg',
	'license' => 'ccbysa20',
	'author' => 'orangeacid',
	'source' => 'http://www.flickr.com/photos/orangeacid/204163563/',
    },

    'kast' => {
	'text' => 'kast',
	'file' => 'Foto_kast.jpg',
	'license' => 'ccbysa20',
	'author' => 'iandexter',
	'source' => 'http://www.flickr.com/photos/iandexter/4912633/',
    },

    'dam' => {
	'text' => 'dam',
	'file' => 'Foto_dam.jpg',
	'license' => 'ccbysa20',
	'author' => 'wannaoreo',
	'source' => 'http://www.flickr.com/photos/wannaoreo/76978976/',
    },

    'mos' => {
	'text' => 'mos',
	'file' => 'Foto_mos.jpg',
	'license' => 'ccbysa20',
	'author' => 'miikas',
	'source' => 'http://www.flickr.com/photos/miikas/229822376/',
    },

    'kus' => {
	'text' => 'kus',
	'file' => 'Foto_kus.jpg',
	'license' => 'ccby20',
	'author' => 'cadmanof50s',
	'source' => 'http://www.flickr.com/photos/cadmanof50s/78339407',
    },

    'hert' => {
	'text' => 'hert',
	'file' => 'Foto_hert.jpg',
	'license' => 'ccbysa20',
	'author' => 'ddebold',
	'source' => 'http://www.flickr.com/photos/ddebold/201514994/',
    },

    'haan' => {
	'text' => 'haan',
	'file' => 'Foto_haan.jpg',
	'license' => 'ccbysa20',
	'author' => '44458147@N00',
	'source' => 'http://www.flickr.com/photos/44458147@N00/246807566/',
    },

    'mast' => {
	'text' => 'mast',
	'file' => 'Foto_mast.jpg',
	'license' => 'ccbysa20',
	'author' => 'irisheyes',
	'source' => 'http://www.flickr.com/photos/irisheyes/24639984/',
    },

    'kip' => {
	'text' => 'kip',
	'file' => 'Foto_kip.jpg',
	'license' => 'pd',
	'author' => 'Sherool',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Rhode_Island_Red.jpg',
    },

    'mist' => {
	'text' => 'mist',
	'file' => 'Foto_mist.jpg',
	'license' => 'ccbysa20',
	'author' => 'aleksey',
	'source' => 'http://www.flickr.com/photos/aleksey/16752326/',
    },

    'wol' => {
	'text' => 'wol',
	'file' => 'Foto_wol.jpg',
	'license' => 'ccbysa20',
	'author' => 'nadiapriestley',
	'source' => 'http://www.flickr.com/photos/nadiapriestley/102709230/',
    },

    'ziek' => {
	'text' => 'ziek',
	'file' => 'Foto_ziek.jpg',
	'license' => 'ccbysa20',
	'author' => 'azadam',
	'source' => 'http://www.flickr.com/photos/azadam/109380081/',
    },

    'meel' => {
	'text' => 'meel',
	'file' => 'Foto_meel.jpg',
	'license' => 'ccbysa20',
	'author' => 'crystalflickr',
	'source' => 'http://www.flickr.com/photos/crystalflickr/39023387/',
    },

    'mol' => {
	'text' => 'mol',
	'file' => 'Foto_mol.jpg',
	'license' => 'ccbysa20',
	'author' => 'zenera',
	'source' => 'http://www.flickr.com/photos/zenera/56677048/',
    },

    'wolk' => {
	'text' => 'wolk',
	'file' => 'Foto_wolk.jpg',
	'license' => 'ccbysa20',
	'author' => 'cobalt',
	'source' => 'http://www.flickr.com/photos/cobalt/203563764/',
    },

    'wolf' => {
	'text' => 'wolf',
	'file' => 'Foto_wolf.jpg',
	'license' => 'pd',
	'author' => '',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Canis_lupus_laying_in_grass.jpp',
    },

    'vlieg' => {
	'text' => 'vlieg',
	'file' => 'Foto_vlieg.jpg',
	'license' => 'ccbysa25',
	'author' => 'Andr&euml Karwath',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Empis_tesselata_male_%28aka%29.jpg',
    },

    'worm' => {
	'text' => 'worm',
	'file' => 'Foto_worm.jpg',
	'license' => 'pd',
	'author' => '',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Earth-worm_1.jpg',
    },

    'paard' => {
	'text' => 'paard',
	'file' => 'Foto_paard.jpg',
	'license' => 'ccbysafa20',
	'author' => 'Jeanot',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Horse_2005-08-06_%28Cheval%29.jpg',
    },

    'brood' => {
	'text' => 'brood',
	'file' => 'Foto_brood.jpg',
	'license' => 'ccbysa20',
	'author' => 'tussius',
	'source' => 'http://www.flickr.com/photos/tussius/126335630/',
    },

    'gum' => {
	'text' => 'gum',
	'file' => 'Foto_gum.jpg',
	'license' => 'ccby20',
	'author' => 'dan4th',
	'source' => 'http://www.flickr.com/photos/dan4th/143657162/',
    },

    'gat' => {
	'text' => 'gat',
	'file' => 'Foto_gat.jpg',
	'license' => 'ccbysa20',
	'author' => 'hugovk',
	'source' => 'http://www.flickr.com/photos/hugovk/25643718/',
    },

    'fiets' => {
	'text' => 'fiets',
	'file' => 'Foto_fiets.jpg',
	'license' => 'gfdl',
	'author' => 'Jared C. Benedict',
	'source' => 'http://en.wikipedia.org/wiki/Image:Mountain_bicycle.jpg',
    },

    'wiel' => {
	'text' => 'wiel',
	'file' => 'Foto_wiel.jpg',
	'license' => 'ccbysa20',
	'author' => 'Sean Lamb',
	'source' => 'http://en.wikipedia.org/wiki/Image:Steam_locomotive_driving_wheel.jpg',
    },

    'trein' => {
	'text' => 'trein',
	'file' => 'Foto_trein.jpg',
	'license' => 'gfdl',
	'author' => 'Ellywa',
	'source' => 'http://nl.wikipedia.org/wiki/Afbeelding:Trein_mat64_alphen_aan_den_rijn_2003.jpg',
    },

    'berg' => {
	'text' => 'berg',
	'file' => 'Foto_berg.jpg',
	'license' => 'ccbysa20',
	'author' => 'paulmannix',
	'source' => 'http://www.flickr.com/photos/paulmannix/261314905/',
    },

    'hiel' => {
	'text' => 'hiel',
	'file' => 'Foto_hiel.jpg',
	'license' => 'ccbysa20',
	'author' => 'berlin78',
	'source' => 'http://www.flickr.com/photos/berlin78/156585499/',
    },

    'vrouw' => {
	'text' => 'vrouw',
	'file' => 'Foto_vrouw.jpg',
	'license' => 'ccbysa20',
	'author' => 'davidden',
	'source' => 'http://www.flickr.com/photos/davidden/137228580/',
    },

    'paal' => {
	'text' => 'paal',
	'file' => 'Foto_paal.jpg',
	'license' => 'ccbysa20',
	'author' => 'darinmarshall',
	'source' => 'http://www.flickr.com/photos/darinmarshall/140509456/',
    },

    'graf' => {
	'text' => 'graf',
	'file' => 'Foto_graf.jpg',
	'license' => 'ccbysa20',
	'author' => 'wka',
	'source' => 'http://www.flickr.com/photos/wka/128192088/',
    },

    'graan' => {
	'text' => 'graan',
	'file' => 'Foto_graan.jpg',
	'license' => 'ccbysa20',
	'author' => 'shareski',
	'source' => 'http://www.flickr.com/photos/shareski/227893693/',
    },

    'kraan' => {
	'text' => 'kraan',
	'file' => 'Foto_kraan.jpg',
	'license' => 'ccbysa20',
	'author' => 'Brett L.',
	'source' => 'http://www.flickr.com/photos/brettlider/54787562/',
    },

    'vat' => {
	'text' => 'vat',
	'file' => 'Foto_vat.jpg',
	'license' => 'ccbysa20',
	'author' => 'sillydog',
	'source' => 'http://www.flickr.com/photos/sillydog/279423883/',
    },

    'kam' => {
	'text' => 'kam',
	'file' => 'Foto_kam.png',
	'license' => 'pd',
	'author' => 'Dub',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Comb.png',
    },
    'poort' => {
	'text' => 'poort',
	'file' => 'Foto_poort.jpg',
	'license' => 'ccbysa20',
	'author' => 'floato',
	'source' => 'http://www.flickr.com/photos/66656285@N00/263333282/',
    },
    'kaars' => {
	'text' => 'kaars',
	'file' => 'Foto_kaars.jpg',
	'license' => 'ccbysa20',
	'author' => 'peterallen',
	'source' => 'http://www.flickr.com/photos/peterallen/129311222/',
    },
    'zwaan' => {
	'text' => 'zwaan',
	'file' => 'Foto_zwaan.jpg',
	'license' => 'pd',
	'author' => 'Sangfroid',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Swan_In_Water.jpg',
    },
    'eend' => {
	'text' => 'eend',
	'file' => 'Foto_eend.jpg',
	'license' => 'pd',
	'author' => 'Oleggivvit',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Male_Mallard.jpg',
    },
    'snoep' => {
	'text' => 'snoep',
	'file' => 'Foto_snoep.jpg',
	'license' => 'ccbysa20',
	'author' => 'firda',
	'source' => 'http://www.flickr.com/photos/firda/64518767/',
    },
    'tent' => {
	'text' => 'tent',
	'file' => 'Foto_tent.jpg',
	'license' => 'ccbysa20',
	'author' => 'photomonkey',
	'source' => 'http://www.flickr.com/photos/photomonkey/20070070/',
    },
    'laars' => {
	'text' => 'laars',
	'file' => 'Foto_laars.jpg',
	'license' => 'ccby20',
	'author' => 'splatt',
	'source' => 'http://www.flickr.com/photos/splatt/234599722/',
    },
    'peen' => {
	'text' => 'peen',
	'file' => 'Foto_peen.jpg',
	'license' => 'gfdl',
	'author' => 'Antoine',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Carotte.JPG',
    },
    'deeg' => {
	'text' => 'deeg',
	'file' => 'Foto_deeg.jpg',
	'license' => 'ccby20',
	'author' => 'afroswede',
	'source' => 'http://www.flickr.com/photos/afroswede/1649766/',
    },
    'feest' => {
	'text' => 'feest',
	'file' => 'Foto_feest.jpg',
	'license' => 'ccbysa20',
	'author' => 'salimfadhley',
	'source' => 'http://www.flickr.com/photos/salimfadhley/108382134/',
    },
    'hoed' => {
	'text' => 'hoed',
	'file' => 'Foto_hoed.jpg',
	'license' => 'pd',
	'author' => 'Frank C. M&uuml;ller',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Borsalino_fcm.jpg',
    },
    'muts' => {
	'text' => 'muts',
	'file' => 'Foto_muts.jpg',
	'license' => 'ccbysa20',
	'author' => 'Yogi',
	'source' => 'http://www.flickr.com/photos/yogi/106434374/in/photostream/',
    },
    'hok' => {
	'text' => 'hok',
	'file' => 'Foto_hok.jpg',
	'license' => 'ccbysa20',
	'author' => 'gullig',
	'source' => 'http://www.flickr.com/photos/gullig/258462712/',
    },
    'kooi' => {
	'text' => 'kooi',
	'file' => 'Foto_kooi.jpg',
	'license' => 'ccbysa20',
	'author' => 'flickerbulb',
	'source' => 'http://www.flickr.com/photos/flickerbulb/136863589/',
    },
    'boon' => {
	'text' => 'boon',
	'file' => 'Foto_boon.jpg',
	'license' => 'pd',
	'author' => 'Hans Bartelds',
	'source' => 'http://en.wikipedia.org/wiki/Image:Psophocarpus_tetragonolobus1.jpg',
    },
    'hol' => {
	'text' => 'hol',
	'file' => 'Foto_hol.jpg',
	'license' => 'ccbysa20',
	'author' => 'blmurch',
	'source' => 'http://www.flickr.com/photos/blmurch/144435176/',
    },
    'want' => {
	'text' => 'want',
	'file' => 'Foto_want.jpg',
	'license' => 'ccbysa20',
	'author' => 'strph',
	'source' => 'http://www.flickr.com/photos/strph/98154806/',
    },
    'zout' => {
	'text' => 'zout',
	'file' => 'Foto_zout.jpg',
	'license' => 'ccby20',
	'author' => 'julianrod',
	'source' => 'http://www.flickr.com/photos/julianrod/176551224/',
    },
    'brug' => {
	'text' => 'brug',
	'file' => 'Foto_brug.jpg',
	'license' => 'gfdl',
	'author' => 'DoubleH',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Nijmegen3.jpg'
    },
    'rug' => {
	'text' => 'rug',
	'file' => 'Foto_rug.jpg',
	'license' => 'ccbysa20',
	'author' => 'trmdttr',
	'source' => 'http://www.flickr.com/photos/trmd/88573080/',
    },
    'wak' => {
	'text' => 'wak',
	'file' => 'Foto_wak.jpg',
	'license' => 'ccby20',
	'author' => 'ulybug',
	'source' => 'http://www.flickr.com/photos/ulybug/100375177/',
    },
    'wiek' => {
	'text' => 'wiek',
	'file' => 'Foto_wiek.jpg',
	'license' => 'pd',
	'author' => '',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Windmuehle.JPG',
    },
    'piet' => {
	'text' => 'piet',
	'file' => 'Foto_piet.jpg',
	'license' => 'gfdl',
	'author' => 'Looi',
	'source' => 'http://nl.wikipedia.org/wiki/Afbeelding:Piet_op_boot.jpg',
    },
    'sint' => {
	'text' => 'sint',
	'file' => 'Foto_sint.jpg',
	'license' => 'ccbysa20',
	'author' => 'Looi',
	'source' => 'http://nl.wikipedia.org/wiki/Afbeelding:Sint_in_spanje.jpg',
    },
    'slee' => {
	'text' => 'slee',
	'file' => 'Foto_slee.jpg',
	'license' => 'ccbysa20',
	'author' => 'miikas',
	'source' => 'http://www.flickr.com/photos/miikas/108678336/',
    },
    'wip' => {
	'text' => 'wip',
	'file' => 'Foto_wip.jpg',
	'license' => 'ccbysa20',
	'author' => 'pikkus',
	'source' => 'http://www.flickr.com/photos/80673360@N00/9643092',
    },
    'zeil' => {
	'text' => 'zeil',
	'file' => 'Foto_zeil.jpg',
	'license' => 'ccbysa20',
	'author' => 'Dana Rocks',
	'source' => 'http://www.flickr.com/photos/sinatra/25916756/',
    },
    'zaag' => {
	'text' => 'zaag',
	'file' => 'Foto_zaag.jpg',
	'license' => 'pd',
	'author' => 'Martink',
	'source' => 'http://nl.wikipedia.org/wiki/Afbeelding:Handzaag.jpg',
    },
    'wit' => {
	'text' => 'wit',
	'file' => 'Tekening_wit.jpg',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'groen' => {
	'text' => 'groen',
	'file' => 'Tekening_groen.jpg',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'grijs' => {
	'text' => 'grijs',
	'file' => 'Tekening_grijs.jpg',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'zwart' => {
	'text' => 'zwart',
	'file' => 'Tekening_zwart.jpg',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'paars' => {
	'text' => 'paars',
	'file' => 'Tekening_paars.jpg',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'rood' => {
	'text' => 'rood',
	'file' => 'Tekening_rood.jpg',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'stoel' => {
	'text' => 'stoel',
	'file' => 'Foto_stoel.jpg',
	'license' => 'gfdl',
	'author' => 'Akir',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Chair.png',
    },
    'bank' => {
	'text' => 'bank',
	'file' => 'Foto_bank.jpg',
	'license' => 'ccbysa20',
	'author' => 'brettlider',
	'source' => 'http://www.flickr.com/photos/brettlider/25120371/',
    },
    'zand' => {
	'text' => 'zand',
	'file' => 'Foto_zand.jpg',
	'license' => 'ccbysa20',
	'author' => '',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Sand_patterns.jpg',
    },
    'pijl' => {
	'text' => 'pijl',
	'file' => 'Foto_pijl.jpg',
	'license' => 'ccbysa20',
	'author' => 'gigijin',
	'source' => 'http://www.flickr.com/photos/gigijin/138367162/',
    },
    'hooi' => {
	'text' => 'hooi',
	'file' => 'Foto_hooi.jpg',
	'license' => 'ccbysa20',
	'author' => 'rsgranne',
	'source' => 'http://www.flickr.com/photos/rsgranne/23779326/',
    },
    'steen' => {
	'text' => 'steen',
	'file' => 'Foto_steen.jpg',
	'license' => 'ccbysa20',
	'author' => 'jankrutisch',
	'source' => 'http://www.flickr.com/photos/jankrutisch/1111111/',
    },
    'steel' => {
	'text' => 'steel',
	'file' => 'Foto_steel.jpg',
	'license' => 'ccbysa20',
	'author' => 'jcoplest',
	'source' => 'http://www.flickr.com/photos/jcoplest/128574895/',
    },
    'stal' => {
	'text' => 'stal',
	'file' => 'Foto_stal.jpg',
	'license' => 'ccbysade20',
	'author' => 'AlexR',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Krippe_crib_family_w_3wisemen.JPG',
    },
    'fruit' => {
	'text' => 'fruit',
	'file' => 'Foto_fruit.jpg',
	'license' => 'ccbysa20',
	'author' => 'brightmeadow',
	'source' => 'http://www.flickr.com/photos/brightmeadow/82505239/',
    },
    'kool' => {
	'text' => 'kool',
	'file' => 'Foto_kool.jpg',
	'license' => 'gfdl',
	'author' => 'Rasbak',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Witte_kool.jpg',
    },
    'bril' => {
	'text' => 'bril',
	'file' => 'Foto_bril.jpg',
	'license' => 'gfdl',
	'author' => 'Nick Fraser',
	'source' => 'http://en.wikipedia.org/wiki/Image:Glassesontable.jpg',
    },
    'peuk' => {
	'text' => 'peuk',
	'file' => 'Foto_peuk.jpg',
	'license' => 'ccby20',
	'author' => 'hive',
	'source' => 'http://www.flickr.com/photos/hive/258104265/',
    },
    'nul' => {
	'text' => 'nul',
	'file' => 'Tekening_nul.png',
	'license' => 'pd',
	'author' => 'syboor',
	'source' => '',
    },
    'riet' => {
	'text' => 'riet',
	'file' => 'Foto_riet.jpg',
	'license' => 'gfdl',
	'author' => 'GerardM',
	'source' => 'http://nl.wikipedia.org/wiki/Afbeelding:Riet.jpg',
    },
    'big' => {
	'text' => 'big',
	'file' => 'Foto_big.jpg',
	'license' => 'ccbysa20',
	'author' => 'MoldovAnn',
	'source' => 'http://www.flickr.com/photos/12417479@N00/12739680/',
    },
    'slot' => {
	'text' => 'slot',
	'file' => 'Foto_slot.jpg',
	'license' => 'ccbysa20',
	'author' => 'trevorblake',
	'source' => 'http://www.flickr.com/photos/trevorblake/14528557/',
    },
    'spel' => {
	'text' => 'spel',
	'file' => 'Foto_spel.jpg',
	'license' => 'pd',
	'author' => 'Francois Haffner',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Clann.jpg',
    },
    'sluis' => {
	'text' => 'sluis',
	'file' => 'Foto_sluis.jpg',
	'license' => 'pd',
	'author' => 'Karel Roose',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Canal_Nieuwpoort-Duinkerke_tidal_lock_Veurne_20030621-002.jpg',
    },
    'gans' => {
	'text' => 'gans',
	'file' => 'Foto_gans.jpg',
	'license' => 'dual',
	'author' => 'Andrzej Barabasz',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Domesticated_goose_AB.jpg',
    },
    'juf' => {
	'text' => 'juf',
	'file' => 'Foto_juf.jpg',
	'license' => 'ccby20',
	'author' => 'Tostie14',
	'source' => 'http://www.flickr.com/photos/tostie14/93877390/',
    },
    'rits' => {
	'text' => 'rits',
	'file' => 'Foto_rits.jpg',
	'license' => 'ccbysa20',
	'author' => 'loungerie',
	'source' => 'http://www.flickr.com/photos/loungerie/42693574/',
    },
    'leeuw' => {
	'text' => 'leeuw',
	'file' => 'Foto_leeuw.jpg',
	'license' => 'ccbysabe20',
	'author' => 'R. Wampers',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Lion_zoo_antwerp_1280.jpg',
    },
    'meeuw' => {
	'text' => 'meeuw',
	'file' => 'Foto_meeuw.jpg',
	'license' => 'ccbysa25',
	'author' => 'Andreas Trepte',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Larus_argentatus_ad.jpg',
    },
    'sneeuw' => {
	'text' => 'sneeuw',
	'file' => 'Foto_sneeuw.jpg',
	'license' => 'ccbysa20',
	'author' => 'tony street',
	'source' => 'http://www.flickr.com/photos/tonystreet/74229022/',
    },
    'duim' => {
	'text' => 'duim',
	'file' => 'Foto_duim.jpg',
	'license' => 'pd',
	'author' => 'Chris 73',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Hand_with_thumbs_up.jpg',
    },
    'pink' => {
	'text' => 'pink',
	'file' => 'Foto_pink.jpg',
	'license' => 'gfdl',
	'author' => 'Michiel1972',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Little_finger.jpg',
    },
    'goud' => {
	'text' => 'goud',
	'file' => 'Foto_goud.jpg',
	'license' => 'pd',
	'author' => 'Swiss Banker',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Goldkey_logo_removed.jpg',
    },
    'kurk' => {
	'text' => 'kurk',
	'file' => 'Foto_kurk.jpg',
	'license' => 'ccbysa20',
	'author' => 'sami73',
	'source' => 'http://www.flickr.com/photos/sami73/125706884/',
    },
    'biet' => {
	'text' => 'biet',
	'file' => 'Foto_biet.jpg',
	'license' => 'ccby20',
	'author' => 'fotodawg',
	'source' => 'http://www.flickr.com/photos/fotodawg/111040816/',
    },
    'zeef' => {
	'text' => 'zeef',
	'file' => 'Foto_zeef.jpg',
	'license' => 'ccbysa20',
	'author' => 'jcoplest',
	'source' => 'http://www.flickr.com/photos/jcoplest/138333126/',
    },
    'kroon' => {
	'text' => 'kroon',
	'file' => 'Foto_kroon.jpg',
	'license' => 'gfdl',
	'author' => 'Robert Pummel',
	'source' => 'http://nl.wikipedia.org/wiki/Afbeelding:De_zogenaamde_kroon_van_Karel_de_Grote_Holy_Roman_Empire_crown_dsc02909.jpg',
    },
    'kerk' => {
	'text' => 'kerk',
	'file' => 'Foto_kerk.jpg',
	'license' => 'ccbysa20',
	'author' => 'hugovk',
	'source' => 'http://www.flickr.com/photos/hugovk/194164077/',
    },
    'pad' => {
	'text' => 'pad',
	'file' => 'Foto_pad.jpg',
	'license' => 'gfdl',
	'author' => 'Taka',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Bufo_bufo_1_%282005_07_11%29.jpg
',
    },
    'duw' => {
	'text' => 'duw',
	'file' => 'Foto_duwen.jpg',
	'license' => 'ccbysa20',
	'author' => 'davosmith',
	'source' => 'http://www.flickr.com/photos/davosmith/31882868/',
    },
    'kuil' => {
	'text' => 'kuil',
	'file' => 'Foto_kuil.jpg',
	'license' => 'ccbysa20',
	'author' => 'redjar',
	'source' => 'http://www.flickr.com/photos/redjar/113348954/',
    },
    'schaar' => {
	'text' => 'schaar',
	'file' => 'Foto_schaar.jpg',
	'license' => 'ccbysa20',
	'author' => 'delta407',
	'source' => 'http://flickr.com/photos/delta407/301194268/',
    },
    'schuur' => {
	'text' => 'schuur',
	'file' => 'Foto_schuur.jpg',
	'license' => 'ccbysa20',
	'author' => 'Izzard',
	'source' => 'http://flickr.com/photos/izzard/247766397/',
    },
    'scheur' => {
	'text' => 'scheur',
	'file' => 'Foto_scheur.jpg',
	'license' => 'ccbysa20',
	'author' => 'dysamoria',
	'source' => 'http://www.flickr.com/photos/dysamoria/291997680/',
    },
    'traan' => {
	'text' => 'traan',
	'file' => 'Foto_traan.jpg',
	'license' => 'ccbysa20',
	'author' => 'Bombardier',
	'source' => 'http://www.flickr.com/photos/bombardier/17183010/',
    },
    'troon' => {
	'text' => 'troon',
	'file' => 'Foto_troon.jpg',
	'license' => 'dual',
	'author' => 'MatthiasKabel',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Ermitage_throne_room_1.jpg',
    },
    'fluit' => {
	'text' => 'fluit',
	'file' => 'Foto_fluit.jpg',
	'license' => 'ccbysa20',
	'author' => 'Anyaka',
	'source' => 'http://www.flickr.com/photos/anyaka/10374923/',
    },
    'kruis' => {
	'text' => 'kruis',
	'file' => 'Foto_kruis.jpg',
	'license' => 'ccby20',
	'author' => 'mrpattersonsir',
	'source' => 'http://www.flickr.com/photos/mrpattersonsir/19865804/',
    },
    'bad' => {
	'text' => 'bad',
	'file' => 'Foto_bad.jpg',
	'license' => 'ccby20',
	'author' => 'drcorneilus',
	'source' => 'http://www.flickr.com/photos/andrec/27840098/',
    },
    'bed' => {
	'text' => 'bed',
	'file' => 'Foto_bed.jpg',
	'license' => 'ccbysa20',
	'author' => 'Aaron Gustafson',
	'source' => 'http://www.flickr.com/photos/aarongustafson/277898305/',
    },
    'bruid' => {
	'text' => 'bruid',
	'file' => 'Foto_bruid.jpg',
	'license' => 'ccbysa20',
	'author' => 'BullyRook',
	'source' => 'http://www.flickr.com/photos/donperryphotographer/156968903/',
    },
    'beul' => {
	'text' => 'beul',
	'file' => 'Foto_beul.jpg',
	'license' => 'ccby20',
	'author' => 'Tammra',
	'source' => 'http://www.flickr.com/photos/tammra/284622135/',
    },
    'slaap' => {
	'text' => 'slaap',
	'file' => 'Foto_slaap.jpg',
	'license' => 'ccbysa20',
	'author' => 'gmenthusiast',
	'source' => 'http://www.flickr.com/photos/gmenthusiast/145989335/',
    },
    'gulp' => {
	'text' => 'gulp',
	'file' => 'Foto_gulp.jpg',
	'license' => 'ccbysa20',
	'author' => 'strph',
	'source' => 'http://www.flickr.com/photos/strph/4356296/',
    },
    'gesp' => {
	'text' => 'gesp',
	'file' => 'Foto_gesp.jpg',
	'license' => 'ccbysa20',
	'author' => 'yogi',
	'source' => 'http://www.flickr.com/photos/yogi/31553798/',
    },
    'la' => {
	'text' => 'la',
	'file' => 'Foto_la.jpg',
	'license' => 'ccbysa20',
	'author' => 'saaby',
	'source' => 'http://www.flickr.com/photos/saaby/34348619/',
    },
    'strand' => {
	'text' => 'strand',
	'file' => 'Foto_strand.jpg',
	'license' => 'ccbysa20',
	'author' => 'javic',
	'source' => 'http://www.flickr.com/photos/javic/110223191/',
    },
    'gang' => {
	'text' => 'gang',
	'file' => 'Foto_gang.jpg',
	'license' => 'ccbysa20',
	'author' => 'wheeldog',
	'source' => 'http://www.flickr.com/photos/dougn/153494421/',
    },
    'loep' => {
	'text' => 'loep',
	'file' => 'Foto_loep.jpg',
	'license' => 'ccbysa20',
	'author' => 'grapatax',
	'source' => 'http://www.flickr.com/photos/grapatax/5841918/',
    },
    'wang' => {
	'text' => 'wang',
	'file' => 'Foto_wang.jpg',
	'license' => 'ccbysa20',
	'author' => 'SpooSpa',
	'source' => 'http://www.flickr.com/photos/spoospa/62323281/',
    },
    'kruk' => {
	'text' => 'kruk',
	'file' => 'Foto_kruk.jpg',
	'license' => 'ccby20',
	'author' => 'thegumblobbist',
	'source' => 'http://www.flickr.com/photos/thegumblobbist/17383607/',
    },
    'lach' => {
	'text' => 'lach',
	'file' => 'Foto_lach.jpg',
	'license' => 'ccbysa20',
	'author' => 'jemsweb',
	'source' => 'http://www.flickr.com/photos/jemsweb/38442835/',
    },
    'tang' => {
	'text' => 'tang',
	'file' => 'Foto_tang.jpg',
	'license' => 'gfdl',
	'author' => 'Retama',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Alicates.jpg',
    },
    'jurk' => {
	'text' => 'jurk',
	'file' => 'Foto_jurk.jpg',
	'license' => 'ccby20',
	'author' => 'darinhercules',
	'source' => 'http://www.flickr.com/photos/darinhercules/273338107/',
    },
    'brein' => {
	'text' => 'brein',
	'file' => 'Foto_brein.jpg',
	'license' => 'pd',
	'author' => '',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Human_brain_NIH.jpg',
    },
    'vuist' => {
	'text' => 'vuist',
	'file' => 'Foto_vuist.jpg',
	'license' => 'ccby20',
	'author' => 'Dabe Murphy',
	'source' => 'http://www.flickr.com/photos/dabemurphy/284256056/',
    },
    'schild' => {
	'text' => 'schild',
	'file' => 'Foto_schild.jpg',
	'license' => 'ccby20',
	'author' => 'Kaptain Kobold',
	'source' => 'http://www.flickr.com/photos/kaptainkobold/108916348/',
    },
    'zwaard' => {
	'text' => 'zwaard',
	'file' => 'Tekening_zwaard.png',
	'license' => 'pd',
	'author' => 'Greentubing',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Sword.svg',
    },
    'luik' => {
	'text' => 'luik',
	'file' => 'Foto_luik.jpg',
	'license' => 'ccbysa20',
	'author' => 'Peter',
	'source' => 'http://www.flickr.com/photos/hejog/193281797/',
    },
    'sla' => {
	'text' => 'sla',
	'file' => 'Foto_sla.jpg',
	'license' => 'ccbysa20',
	'author' => 'Aine D',
	'source' => 'http://www.flickr.com/photos/dainec/14954708/',
    },
    'slak' => {
	'text' => 'slak',
	'file' => 'Foto_slak.jpg',
	'license' => 'ccbysa20',
	'author' => 'tamburix',
	'source' => 'http://www.flickr.com/photos/tamburix/24445089/',
    },
    'wieg' => {
	'text' => 'wieg',
	'file' => 'Foto_wieg.jpg',
	'license' => 'ccbysa20',
	'author' => 'Augie Schwer',
	'source' => 'http://www.flickr.com/photos/augie/219442465/',
    },
    'klas' => {
	'text' => 'klas',
	'file' => 'Foto_klas.jpg',
	'license' => 'ccbysa20',
	'author' => 'kafka4prez',
	'source' => 'http://www.flickr.com/photos/kafka4prez/200832376/',
    }, 
	'pop' => {
	'text' => 'pop',
	'file' => 'Foto_pop.jpg',
	'license' => 'dual',
	'author' => 'forestfulighting',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Decthirtyohfive_158.jpg',
    },
	'pet' => {
	'text' => 'pet',
	'file' => 'Foto_pet.jpg',
	'license' => 'ccby20',
	'author' => 'sidscool',
	'source' => 'http://www.flickr.com/photos/lifeiscooldude/99730195/',
    },  
	'dop' => {
	'text' => 'dop',
	'file' => 'Foto_dop.jpg',
	'license' => 'ccbysa20',
	'author' => 'caseywest',
	'source' => 'http://www.flickr.com/photos/caseywest/375964328/',
    },
	'das' => {
	'text' => 'das',
	'file' => 'Foto_das.jpg',
	'license' => 'pd',
	'author' => '',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Dachs.jpg',
    },
	'saus' => {
	'text' => 'saus',
	'file' => 'Foto_saus.jpg',
	'license' => 'ccby20',
	'author' => 'endurancerider',
	'source' => 'http://www.flickr.com/photos/endurancerider/340016865/',
    },
	'ruit' => {
	'text' => 'ruit',
	'file' => 'Foto_ruit.jpg',
	'license' => 'ccby20',
	'author' => 'rick',
	'source' => 'http://www.flickr.com/photos/spine/248838985/',
    },
	'haai' => {
	'text' => 'haai',
	'file' => 'Foto_haai.jpg',
	'license' => 'ccby20',
	'author' => 'StormyDog',
	'source' => 'http://www.flickr.com/photos/the-lees/134610871/',
    },
	'friet' => {
	'text' => 'friet',
	'file' => 'Foto_friet.jpg',
	'license' => 'ccbysa20',
	'author' => 'jjsawrey',
	'source' => 'http://www.flickr.com/photos/pancakejess/273596409/',
    },
	'koets' => {
	'text' => 'koets',
	'file' => 'Foto_koets.jpg',
	'license' => 'ccbysa10',
	'author' => 'Jason L. Buberal',
	'source' => 'http://nl.wikipedia.org/wiki/Afbeelding:Buberel_Coronation_coach_Catherine_the_Great.jpg',
    },
	'stad' => {
	'text' => 'stad',
	'file' => 'Foto_stad.jpg',
	'license' => 'pd',
	'author' => '',
	'source' => 'http://commons.wikimedia.org/wiki/Image:SLCTown.jpg',
    },
	'drop' => {
	'text' => 'drop',
	'file' => 'Foto_drop.jpg',
	'license' => 'ccby20',
	'author' => 'Pikaluk',
	'source' => 'http://www.flickr.com/photos/pikaluk/9571257/',
    },
	'dorp' => {
	'text' => 'dorp',
	'file' => 'Foto_dorp.jpg',
	'license' => 'ccby20',
	'author' => 'ippei + janine',
	'source' => 'http://www.flickr.com/photos/ippei-janine/256030135/',
    },
	'klei' => {
	'text' => 'klei',
	'file' => 'Foto_klei.jpg',
	'license' => 'ccbysa20',
	'author' => 'Mujib',
	'source' => 'http://www.flickr.com/photos/mujib/434202/',
    },
	'klomp' => {
	'text' => 'klomp',
	'file' => 'Foto_klomp.jpg',
	'license' => 'pd',
	'author' => 'Kuchen',
	'source' => 'http://commons.wikimedia.org/wiki/Image:Clog-Berkemann-white.jpg',
    },
	'som' => {
	'text' => 'som',
	'file' => 'Tekening_som.png',
	'license' => 'pd',
	'author' => '',
	'source' => '',
    },
	'os' => {
	'text' => 'os',
	'file' => 'Foto_os.jpg',
	'license' => 'ccbysa20',
	'author' => 'jurek d.',
	'source' => 'http://www.flickr.com/photos/jurek_durczak/145014791/',
    },
	'' => {
	'text' => '',
	'file' => '',
	'license' => 'ccbysa20',
	'author' => '',
	'source' => '',
    },
	'' => {
	'text' => '',
	'file' => '',
	'license' => 'ccbysa20',
	'author' => '',
	'source' => '',
    },
	'' => {
	'text' => '',
	'file' => '',
	'license' => 'ccbysa20',
	'author' => '',
	'source' => '',
    },
#    '' => {
#	'text' => '',
#	'file' => '',
#	'license' => 'ccbysa20',
#	'author' => '',
#	'source' => '',
#    },

};

